#!/usr/bin/env bash
# Resolve the argument shapes of the Cold War builtins found in ate47's function
# table, by finding what STOCK SCRIPT does with them in the decompiled dump.
#
#   ! bash tools/dump-grep.sh                    # dump at ../bocw-source-main
#   ! bash tools/dump-grep.sh /c/path/to/dump    # or say where it is
#
# Writes dump-report.md next to the repo. Paste that back into the session.
#
# WHY. docs/notes/cw-builtins.md names builtins whose ARGUMENTS are unknown -
# setteam takes one argument, but a team name, an index and an entity are all
# one argument. Writing a test script against a guess is how the last three
# game-crashing defects happened (src/README.md -> "What a harness PASS does and
# does not mean"). A stock call site settles it in one line.
#
# READ-ONLY. Greps a local dump. Touches no game, no network, no repo file.

set -u

DUMP="${1:-$(cd "$(dirname "$0")/../.." && pwd)/bocw-source-main}"
OUT="$(cd "$(dirname "$0")/.." && pwd)/dump-report.md"

if [ ! -d "$DUMP" ]; then
    echo "NOT FOUND: $DUMP"
    echo "Pass the dump path: bash tools/dump-grep.sh /c/path/to/bocw-source-main"
    exit 1
fi

# scripts/ is the 29 MB name-resolved tree; hashed/ is the rest. Search both -
# a hashed file still shows argument shape even if its own name is a hash.
ROOTS=""
[ -d "$DUMP/scripts" ] && ROOTS="$ROOTS $DUMP/scripts"
[ -d "$DUMP/hashed" ]  && ROOTS="$ROOTS $DUMP/hashed"
[ -z "$ROOTS" ] && ROOTS="$DUMP"

echo "dump:   $DUMP"
echo "roots: $ROOTS"
echo "out:    $OUT"
echo

# $1 heading, $2 regex, $3 max sample lines
#
# ⚠ Patterns match the CALL ONLY, with no caller prefix. An earlier version tried
# to capture `player setteam(...)` with a leading [A-Za-z_.\[\]0-9]* class - but in
# POSIX ERE the `]` inside that class TERMINATES the bracket expression, so the
# pattern silently searched for the literal text `0-9]` and matched nothing at all.
# grep -n prints the whole line regardless, so the caller is visible for free.
section() {
    printf '\n## %s\n\n' "$1" >> "$OUT"
    n=$(grep -rEoh "$2" $ROOTS --include='*.gsc' --include='*.csc' 2>/dev/null | wc -l | tr -d ' ')
    printf '**%s call site(s).**\n\n' "$n" >> "$OUT"
    if [ "$n" = "0" ]; then
        printf '_No stock script calls it. The builtin may still exist - the engine exports it - but\nthe dump cannot tell us the argument shape._\n' >> "$OUT"
        echo "  $1: 0"
        return
    fi
    printf '```gsc\n' >> "$OUT"
    grep -rEn "$2" $ROOTS --include='*.gsc' --include='*.csc' 2>/dev/null \
        | sed "s#^$DUMP/##" | head -"$3" >> "$OUT"
    printf '```\n' >> "$OUT"
    echo "  $1: $n"
}

cat > "$OUT" <<HDR
# Dump grep report

Generated by \`tools/dump-grep.sh\` against \`$DUMP\`.
Resolves argument shapes for the builtins in \`docs/notes/cw-builtins.md\`.

> A line like \`player setteam( "allies" )\` says the arg is a team NAME and the
> caller is the player entity. A line like \`setteam( 2 )\` says something else
> entirely. That difference is the whole point of this report.
HDR

echo "grepping..."

# ── The four the test queue is blocked on ────────────────────────────────────
section "setteam — arg shape is what blocks test C8" \
        '\bsetteam *\([^)]*\)' 60
section "getteam" \
        '\bgetteam *\([^)]*\)' 25
section "addtestclient — blocks test C7 (bots, and the real client ceiling)" \
        '\baddtestclient *\([^)]*\)' 40
section "map_restart — blocks test B4 (can cwpatch be dropped?)" \
        '\bmap_restart *\([^)]*\)' 40
section "getnumexpectedplayers" \
        '\bgetnumexpectedplayers *\([^)]*\)' 30

# ── getgametypesetting with MORE THAN ONE argument ───────────────────────────
# The table says 1-10 args. Every call in this project passes one. A top-level
# comma inside the parens means a stock call passes more, which is the cheapest
# lead on what the other nine do.
section "getgametypesetting with >1 argument (table says 1-10; we always pass 1)" \
        '\bgetgametypesetting *\([^)]*,[^)]*\)' 40

# ── The other new builtins, for completeness ─────────────────────────────────
section "numremoteclients / getnumconnectedplayers" \
        '\b(numremoteclients|getnumconnectedplayers) *\([^)]*\)' 30
section "isvalidgametype / getgametypeenumfromname / forcegamemodemappings" \
        '\b(isvalidgametype|getgametypeenumfromname|forcegamemodemappings) *\([^)]*\)' 40
section "switchmap_* — does ANY stock script use them?" \
        '\bswitchmap_[a-z]* *\([^)]*\)' 40
section "sessionmodeisprivate*" \
        '\bsessionmodeisprivate[a-z]* *\([^)]*\)' 20
section "kick — the only obvious undo for addtestclient" \
        '\bkick *\([^)]*\)' 25
section "allowspectateteam / allowspectateallteams / spawnspectator" \
        '\b(allowspectateteam|allowspectateallteams|spawnspectator) *\([^)]*\)' 30

# ── BONUS: does the dump already name a larger Gunfight variant? ─────────────
# If a gunfight_4v4 / _5v5 string exists in stock script, that pre-answers the
# headline of lobby_probe (test A1) with no game at all.
printf '\n## Gunfight gametype strings present in the dump\n\n' >> "$OUT"
printf 'If anything beyond `gunfight` and `gunfight_3v3` appears here, it pre-answers the\nheadline of `lobby_probe` (test A1) with no game required.\n\n```\n' >> "$OUT"
grep -rEoh '"gunfight[a-z0-9_]*"|#"gunfight[a-z0-9_]*"' $ROOTS --include='*.gsc' --include='*.csc' 2>/dev/null \
    | sort | uniq -c | sort -rn >> "$OUT"
printf '```\n' >> "$OUT"
echo "  gunfight strings: $(grep -rEoh '"gunfight[a-z0-9_]*"' $ROOTS --include='*.gsc' 2>/dev/null | sort -u | wc -l | tr -d ' ') distinct"

# ── The 6+2 split: where does 3-per-team actually come from? ─────────────────
section "team_assignment: the max_players gate (is 3-per-team anywhere explicit?)" \
        '\b(function_efe5a681|max_players|team_players) *[^;]*' 50

printf '\n---\n\nGenerated read-only. No game state touched.\n' >> "$OUT"

echo
echo "WROTE: $OUT"
echo "Paste it back, or: cat \"$OUT\""
